<simple> ::= (ws mul)* ws?
<conditional> ::= (aws mul)* aws?

mul ::= (<"mul("> digit <","> digit <")">)
<ignore> ::= stop (!start any)* (start | eol)

<stop> ::= <"don't()">
<start> ::= <"do()">

<digit> ::= #"\d{1,3}"
<ws> ::= (!mul any)*
<aws> ::= (ignore / (!mul !ignore any))*
<eol> ::= #"$"
<any> ::= <#"."> | <#"\n">
